name: Automated wokflow

on:
  pull_request:
    paths-ignore:
      - '.github/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  pullrequest:
    permissions:
      contents: write
      packages: write
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: Wivik/pyp-boy/.github/workflows/release.yml@main
