name: Clean old packages

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'pyp-boy'
          package-type: 'container'
          min-versions-to-keep: 2

